### ISSUE TITLE
[Java] Util entity 고도화

### ISSUE THREAD

**Issue by HAN-SEOHYUN** [IDWWT/hello-utils#68]
## 요구사항
Util entity 고도화

## tasks
- [ ] util_id start number 1 ?
- [ ] 컬럼별 데이터 형식 Column 어노테이션 활용하여 설정
- [ ] not null 명시
- [ ] Base Entity 생성하여 extends 하도록 변경
